/* global use, db */
// MongoDB Playground
// To disable this template go to Settings | MongoDB | Use Default Template For Playground.
// Make sure you are connected to enable completions and to be able to run a playground.
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.
// The result of the last command run in a playground is shown on the results panel.
// By default the first 20 documents will be returned with a cursor.
// Use 'console.log()' to print to the debug output.
// For more documentation on playgrounds please refer to
// https://www.mongodb.com/docs/mongodb-vscode/playgrounds/

// Select the database to use.

use("Westbound");
const now = new Date();

db.items.createIndex({ name: 1 }, { unique: true });

// db.items.insertOne({
//     name: "Opium Sack",
//     description: "A small sack filled with dried opium, a potent narcotic.",
//     image: "opium_sack.png",
//     effect: "Contains enough opium for multiple uses.",
//     value: {
//       currentValue: 50,
//       dailyChange: 0,
//       monthlyChange: 0,
//       yearlyChange: 0,
//       vender: {
//         venderBuy: 100,
//         venderSell: 60,
//         totalVendered: 1500,
//         balanceOfPaymentsTotal: 3000
//       }
//     },
//     circulation: 400,
//     category: "Intoxicants", // Opium item
//     equippable: false,
//     baseArmourValue: 0,
//     damage: 0,
//     baseChanceToHit: 0,
//     consumable: false,
//     stackable: true,
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   });

// db.items.insertOne({
//     name: "Tobacco Sack",
//     description: "A sack filled with dried tobacco leaves, ready for use.",
//     image: "tobacco_sack.png",
//     effect: "Contains enough tobacco for multiple uses.",
//     value: {
//       currentValue: 30,
//       dailyChange: 0,
//       monthlyChange: 0,
//       yearlyChange: 0,
//       vender: {
//         venderBuy: 60,
//         venderSell: 40,
//         totalVendered: 1000,
//         balanceOfPaymentsTotal: 2000
//       }
//     },
//     circulation: 300,
//     category: "Intoxicants", // Tobacco item
//     equippable: false,
//     baseArmourValue: 0,
//     damage: 0,
//     baseChanceToHit: 0,
//     consumable: false,
//     stackable: true,
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   });

// db.items.insertOne({
//     name: "Morphine",
//     description: "A potent painkiller derived from opium. Widely used by doctors and frontier surgeons, but known for its addictive properties.",
//     image: "morphine_bottle.png",
//     effect: "Used to numb intense pain. Frequent use can lead to dependency and addiction.",
//     value: {
//       currentValue: 75,
//       dailyChange: 0,
//       monthlyChange: 0,
//       yearlyChange: 0,
//       vender: {
//         venderBuy: 150,
//         venderSell: 90,
//         totalVendered: 800,
//         balanceOfPaymentsTotal: 12000
//       }
//     },
//     circulation: 200,
//     category: "Intoxicants", // Morphine item
//     equippable: false,
//     baseArmourValue: 0,
//     damage: 0,
//     baseChanceToHit: 0,
//     consumable: true,
//     stackable: false,
//     createdAt: new Date(),
//     updatedAt: new Date()
//   });

// db.items.insertOne({
//     name: "Peyote Button",
//     description: "A dried button of the peyote cactus, used in spiritual ceremonies for its hallucinogenic properties.",
//     image: "peyote_button.png",
//     effect: "Induces vivid hallucinations and alters perception when consumed.",
//     value: {
//       currentValue: 30,
//       dailyChange: 0,
//       monthlyChange: 1,
//       yearlyChange: 5,
//       vender: {
//         venderBuy: 50,
//         venderSell: 25,
//         totalVendered: 800,
//         balanceOfPaymentsTotal: 2000,
//       },
//     },
//     circulation: 300,
//     category: "Intoxicants", // Peyote item
//     equippable: false,
//     baseArmourValue: 0,
//     damage: 0,
//     baseChanceToHit: 0,
//     consumable: true,
//     stackable: true,
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   });

//   db.items.insertOne({
//     name: "Cannabis",
//     description: "A small bundle of dried cannabis leaves, known for its relaxing and calming effects.",
//     image: "cannabis_bundle.png",
//     effect: "Relieves stress and induces mild euphoria when smoked or ingested.",
//     value: {
//       currentValue: 20,
//       dailyChange: 0,
//       monthlyChange: -1,
//       yearlyChange: 2,
//       vender: {
//         venderBuy: 40,
//         venderSell: 15,
//         totalVendered: 1200,
//         balanceOfPaymentsTotal: 1800,
//       },
//     },
//     circulation: 500,
//     category: "Intoxicants", // Cannabis item
//     equippable: false,
//     baseArmourValue: 0,
//     damage: 0,
//     baseChanceToHit: 0,
//     consumable: true,
//     stackable: true,
//     createdAt: new Date(),
//     updatedAt: new Date(),
//   });

// db.items.insertMany([
//     {
//       name: "Pickaxe",
//       description: "Extracts ore, gemstones, and minerals.",
//       image: "pickaxe.png",
//       effect: "Used in mining operations to gather valuable resources.",
//       tier:"",
//       value: {
//         currentValue: 20,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 30,
//           venderSell: 15,
//           totalVendered: 0,
//           balanceOfPaymentsTotal: 0,
//         },
//       },
//       circulation: 100,
//       category: "Tools",
//       equippable: false,
//       baseArmourValue: 0,
//       damage: 0,
//       baseChanceToHit: 0,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Shovel",
//       description: "Uncovers buried treasures or fossils.",
//       image: "shovel.png",
//       effect: "Needed for excavation activities like setting traps or digging wells.",
//       tier:"",
//       value: {
//         currentValue: 15,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 25,
//           venderSell: 10,
//           totalVendered: 0,
//           balanceOfPaymentsTotal: 0,
//         },
//       },
//       circulation: 120,
//       category: "Tools",
//       equippable: false,
//       baseArmourValue: 0,
//       damage: 0,
//       baseChanceToHit: 0,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Gold Pan",
//       description: "Sifts through river sediments for gold nuggets.",
//       image: "gold_pan.png",
//       effect: "Essential for prospecting in riverbeds and creeks.",
//       tier:"",
//       value: {
//         currentValue: 10,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 20,
//           venderSell: 5,
//           totalVendered: 0,
//           balanceOfPaymentsTotal: 0,
//         },
//       },
//       circulation: 80,
//       category: "Tools",
//       equippable: false,
//       baseArmourValue: 0,
//       damage: 0,
//       baseChanceToHit: 0,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Hatchet",
//       description: "Chops down trees for crafting materials like timber.",
//       image: "hatchet.png",
//       effect: "Collects wood for crafting and kindling for fires.",
//       tier:"",
//       value: {
//         currentValue: 18,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 28,
//           venderSell: 12,
//           totalVendered: 0,
//           balanceOfPaymentsTotal: 0,
//         },
//       },
//       circulation: 90,
//       category: "Tools",
//       equippable: false,
//       baseArmourValue: 0,
//       damage: 0,
//       baseChanceToHit: 0,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Fishing Rod",
//       description: "Catches fish from water bodies.",
//       image: "fishing_rod.png",
//       effect: "Requires bait to be functional, used for fishing.",
//       tier:"",
//       value: {
//         currentValue: 25,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 35,
//           venderSell: 20,
//           totalVendered: 0,
//           balanceOfPaymentsTotal: 0,
//         },
//       },
//       circulation: 70,
//       category: "Tools",
//       equippable: false,
//       baseArmourValue: 0,
//       damage: 0,
//       baseChanceToHit: 0,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     db.items.insertOne({
//         name: "Sickle and Basket",
//         description: "A sturdy sickle paired with a woven basket, perfect for harvesting crops and collecting them in one go.",
//         image: "sickle_and_basket.png",
//         effect: "Harvest crops efficiently and store them directly into the basket.",
//         value: {
//           currentValue: 25,
//           dailyChange: 0,
//           monthlyChange: 0,
//           yearlyChange: 0,
//           vender: {
//             venderBuy: 50,
//             venderSell: 30,
//             totalVendered: 200,
//             balanceOfPaymentsTotal: 6000
//           }
//         },
//         circulation: 300,
//         category: "Tools",
//         equippable: false,
//         baseArmourValue: 0,
//         damage: 0,
//         baseChanceToHit: 0,
//         consumable: false,
//         stackable: false,
//         createdAt: new Date(),
//         updatedAt: new Date()
//       });

//     db.items.insertMany([
//         {
//           name: "Whiskey",
//           description: "A strong distilled spirit made from fermented grain mash, known for its rich flavor and warming effects.",
//           image: "whiskey.png",
//           effect: "Provides a temporary boost to courage and warmth.",
//           value: {
//             currentValue: 10,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 20,
//               venderSell: 15,
//               totalVendered: 1000,
//               balanceOfPaymentsTotal: 5000,
//             },
//           },
//           circulation: 500,
//           category: "Alcohol",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Bourbon",
//           description: "A smooth and sweet spirit, aged in charred oak barrels for a rich caramel flavor.",
//           image: "bourbon.png",
//           effect: "Increases stamina and helps with stress relief for a short time.",
//           value: {
//             currentValue: 12,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 25,
//               venderSell: 18,
//               totalVendered: 800,
//               balanceOfPaymentsTotal: 4000,
//             },
//           },
//           circulation: 400,
//           category: "Alcohol",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Moonshine",
//           description: "A homemade, illegal liquor made from corn or fruit, with a powerful and harsh taste.",
//           image: "moonshine.png",
//           effect: "Temporarily increases strength, but causes dizziness after consumption.",
//           value: {
//             currentValue: 8,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 15,
//               venderSell: 10,
//               totalVendered: 1200,
//               balanceOfPaymentsTotal: 6000,
//             },
//           },
//           circulation: 700,
//           category: "Alcohol",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Rum",
//           description: "A sweet, distilled alcoholic beverage made from sugarcane byproducts, often enjoyed by sailors and pirates.",
//           image: "rum.png",
//           effect: "Temporarily boosts morale and reduces fatigue.",
//           value: {
//             currentValue: 9,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 18,
//               venderSell: 12,
//               totalVendered: 950,
//               balanceOfPaymentsTotal: 4500,
//             },
//           },
//           circulation: 600,
//           category: "Alcohol",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Cider",
//           description: "A fermented beverage made from apples, offering a refreshing and mildly sweet flavor.",
//           image: "cider.png",
//           effect: "Provides a light mood boost and a slight increase in dexterity.",
//           value: {
//             currentValue: 7,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 12,
//               venderSell: 8,
//               totalVendered: 1100,
//               balanceOfPaymentsTotal: 4500,
//             },
//           },
//           circulation: 650,
//           category: "Alcohol",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         }
//       ]);

//     db.items.insertMany([
//         {
//           name: "Bandage",
//           description: "A simple cloth used to cover and protect wounds, helping to stop bleeding and promote healing.",
//           image: "bandage.png",
//           effect: "Heals minor wounds over time.",
//           value: {
//             currentValue: 5,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 10,
//               venderSell: 5,
//               totalVendered: 500,
//               balanceOfPaymentsTotal: 2500,
//             },
//           },
//           circulation: 800,
//           category: "Medical",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Healing Salve",
//           description: "A medicinal ointment used for treating cuts, burns, and other minor injuries.",
//           image: "healing_salve.png",
//           effect: "Restores health by treating minor injuries over time.",
//           value: {
//             currentValue: 12,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 25,
//               venderSell: 15,
//               totalVendered: 300,
//               balanceOfPaymentsTotal: 4500,
//             },
//           },
//           circulation: 450,
//           category: "Medical",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "First Aid Kit",
//           description: "A well-equipped kit containing various medical supplies such as bandages, antiseptics, and gauze for treating injuries.",
//           image: "first_aid_kit.png",
//           effect: "Provides comprehensive healing for moderate injuries.",
//           value: {
//             currentValue: 25,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 60,
//               venderSell: 40,
//               totalVendered: 200,
//               balanceOfPaymentsTotal: 8000,
//             },
//           },
//           circulation: 300,
//           category: "Medical",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: false,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Antidote",
//           description: "A mixture designed to treat poisoning from snake bites or toxic plants.",
//           image: "antidote.png",
//           effect: "Cures poison or venom from toxic substances.",
//           value: {
//             currentValue: 15,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 35,
//               venderSell: 25,
//               totalVendered: 150,
//               balanceOfPaymentsTotal: 3750,
//             },
//           },
//           circulation: 200,
//           category: "Medical",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: false,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         },
//         {
//           name: "Painkiller",
//           description: "A powerful pain-relieving pill used to temporarily alleviate pain from injuries.",
//           image: "painkiller.png",
//           effect: "Reduces pain, allowing the user to function despite injuries.",
//           value: {
//             currentValue: 8,
//             dailyChange: 0,
//             monthlyChange: 0,
//             yearlyChange: 0,
//             vender: {
//               venderBuy: 20,
//               venderSell: 12,
//               totalVendered: 700,
//               balanceOfPaymentsTotal: 14000,
//             },
//           },
//           circulation: 600,
//           category: "Medical",
//           equippable: false,
//           baseArmourValue: 0,
//           damage: 0,
//           baseChanceToHit: 0,
//           consumable: true,
//           stackable: true,
//           createdAt: new Date(),
//           updatedAt: new Date(),
//         }
//       ]);

//       db.items.insertOne({
//         name: "Large First Aid Kit",
//         description: "A large, comprehensive first aid kit containing advanced medical supplies such as bandages, antiseptics, splints, and other tools for treating serious injuries.",
//         image: "large_first_aid_kit.png",
//         effect: "Provides extensive healing for severe injuries and multiple wounds.",
//         value: {
//           currentValue: 50,
//           dailyChange: 0,
//           monthlyChange: 0,
//           yearlyChange: 0,
//           vender: {
//             venderBuy: 100,
//             venderSell: 70,
//             totalVendered: 100,
//             balanceOfPaymentsTotal: 7000,
//           },
//         },
//         circulation: 150,
//         category: "Medical",
//         equippable: false,
//         baseArmourValue: 0,
//         damage: 0,
//         baseChanceToHit: 0,
//         consumable: true,
//         stackable: false,
//         createdAt: new Date(),
//         updatedAt: new Date(),
//       });

//   db.items.insertMany([
//     {
//       name: "Winchester Rifle",
//       description: "A lever-action rifle known for its reliability and iconic status in the Wild West.",
//       image: "winchester_rifle.png",
//       effect: "Delivers high accuracy and damage over long distances.",
//       value: {
//         currentValue: 150,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 300,
//           venderSell: 200,
//           totalVendered: 50,
//           balanceOfPaymentsTotal: 10000,
//         },
//       },
//       circulation: 120,
//       category: "Primary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 90,
//       baseChanceToHit: 85,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Double-Barrel Shotgun",
//       description: "A powerful shotgun designed for close-range combat, perfect for defending your homestead.",
//       image: "double_barrel_shotgun.png",
//       effect: "Deals devastating damage at close range.",
//       value: {
//         currentValue: 120,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 240,
//           venderSell: 180,
//           totalVendered: 75,
//           balanceOfPaymentsTotal: 13500,
//         },
//       },
//       circulation: 100,
//       category: "Primary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 110,
//       baseChanceToHit: 70,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Carbine",
//       description: "A single-shot breech-loading rifle favored by sharpshooters for its accuracy.",
//       image: "sharps_carbine.png",
//       effect: "Offers precision targeting for long-range engagements.",
//       value: {
//         currentValue: 140,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 280,
//           venderSell: 210,
//           totalVendered: 60,
//           balanceOfPaymentsTotal: 12600,
//         },
//       },
//       circulation: 90,
//       category: "Primary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 95,
//       baseChanceToHit: 88,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Repeating Rifle",
//       description: "A reliable repeating rifle with a high rate of fire, ideal for sustained combat.",
//       image: "henry_repeating_rifle.png",
//       effect: "Allows for quick follow-up shots with moderate damage.",
//       value: {
//         currentValue: 160,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 320,
//           venderSell: 240,
//           totalVendered: 55,
//           balanceOfPaymentsTotal: 13200,
//         },
//       },
//       circulation: 110,
//       category: "Primary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 80,
//       baseChanceToHit: 80,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Buffalo Rifle",
//       description: "A heavy-caliber rifle used for hunting large game, offering extreme power and range.",
//       image: "buffalo_rifle.png",
//       effect: "Inflicts massive damage at extreme distances.",
//       value: {
//         currentValue: 180,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 360,
//           venderSell: 270,
//           totalVendered: 40,
//           balanceOfPaymentsTotal: 10800,
//         },
//       },
//       circulation: 70,
//       category: "Primary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 120,
//       baseChanceToHit: 75,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//   ]);

// db.items.insertMany([
//     {
//       name: "Revolver",
//       description: "A classic six-shooter revolver, reliable and quick to draw for any cowboy.",
//       image: "revolver.png",
//       effect: "Delivers consistent damage at close to medium range.",
//       value: {
//         currentValue: 100,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 200,
//           venderSell: 150,
//           totalVendered: 120,
//           balanceOfPaymentsTotal: 18000,
//         },
//       },
//       circulation: 300,
//       category: "Secondary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 60,
//       baseChanceToHit: 85,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Derringer",
//       description: "A small, easily concealable pistol, perfect for self-defense in a pinch.",
//       image: "derringer.png",
//       effect: "Light damage but quick to draw and use in tight situations.",
//       value: {
//         currentValue: 70,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 140,
//           venderSell: 100,
//           totalVendered: 200,
//           balanceOfPaymentsTotal: 20000,
//         },
//       },
//       circulation: 500,
//       category: "Secondary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 40,
//       baseChanceToHit: 90,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Sawed-Off Shotgun",
//       description: "A compact shotgun offering devastating power at extremely close range.",
//       image: "sawed_off_shotgun.png",
//       effect: "High damage but limited range and accuracy.",
//       value: {
//         currentValue: 120,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 240,
//           venderSell: 180,
//           totalVendered: 80,
//           balanceOfPaymentsTotal: 14400,
//         },
//       },
//       circulation: 150,
//       category: "Secondary Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 90,
//       baseChanceToHit: 65,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     }
//   ]);

// db.items.insertMany([
//     {
//       name: "Pocket Knife",
//       description: "A sharp and versatile knife, useful for self-defense and various tasks.",
//       image: "pocket_knife.png",
//       effect: "Low damage but reliable in close-quarters combat.",
//       value: {
//         currentValue: 30,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 60,
//           venderSell: 40,
//           totalVendered: 300,
//           balanceOfPaymentsTotal: 12000,
//         },
//       },
//       circulation: 700,
//       category: "Melee Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 25,
//       baseChanceToHit: 95,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Throwing Knives",
//       description: "A set of balanced knives, designed for accuracy and quick deployment.",
//       image: "throwing_knives.png",
//       effect: "Moderate damage with precision in close combat.",
//       value: {
//         currentValue: 80,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 160,
//           venderSell: 120,
//           totalVendered: 150,
//           balanceOfPaymentsTotal: 18000,
//         },
//       },
//       circulation: 500,
//       category: "Melee Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 40,
//       baseChanceToHit: 90,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     },
//     {
//       name: "Bowie Knife",
//       description: "A large and formidable knife with a sharp blade, often carried for hunting and combat.",
//       image: "bowie_knife.png",
//       effect: "High damage in close quarters with excellent durability.",
//       value: {
//         currentValue: 100,
//         dailyChange: 0,
//         monthlyChange: 0,
//         yearlyChange: 0,
//         vender: {
//           venderBuy: 200,
//           venderSell: 150,
//           totalVendered: 90,
//           balanceOfPaymentsTotal: 13500,
//         },
//       },
//       circulation: 250,
//       category: "Melee Weapon",
//       equippable: true,
//       baseArmourValue: 0,
//       damage: 60,
//       baseChanceToHit: 80,
//       consumable: false,
//       stackable: false,
//       createdAt: new Date(),
//       updatedAt: new Date(),
//     }
//   ]);
